name: CI

on: 
  push:
    branches:
      - main
      - release/**

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/**

jobs:
  build_android:
    name: Build Android Unsigned
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0 
      - name: Install Dependencies
        uses: "./.github/workflows/steps/install_dependencies"
      
      - name: Build Mobile (Android)
        uses: "./.github/workflows/steps/build_mobile"
        with:
          package-id: "Android"
          project-to-build: "MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.csproj" 
          target-framework: "net6.0-android"

  build_ios:
    name: Build iOS
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0 
      - name: Install Dependencies
        uses: "./.github/workflows/steps/install_dependencies"
      
      - name: Build Mobile (iOS)
        uses: "./.github/workflows/steps/build_mobile"
        with:
          package-id: "Mobile_iOS"
          project-to-build: "MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.csproj" 
          target-framework: "net6.0-ios"

  build_maccatalyst:
    name: Build MacCatalyst
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0 
      - name: Install Dependencies
        uses: "./.github/workflows/steps/install_dependencies"
      
      - name: Build Mobile (MacCatalyst)
        uses: "./.github/workflows/steps/build_mobile"
        with:
          package-id: "Mobile_MacCatalyst"
          project-to-build: "MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.csproj" 
          target-framework: "net6.0-maccatalyst"

  build_wasm:
    name: Build Wasm
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0 
      - name: Install Dependencies
        uses: "./.github/workflows/steps/install_dependencies"
      
      - name: Build Wasm
        uses: "./.github/workflows/steps/build_wasm"
        with:
          package-id: "Wasm"
          project-to-build: "MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.csproj" 

  build_windows_unsigned:
    name: Build Windows Unsigned
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0 
      - name: Install Dependencies
        uses: "./.github/workflows/steps/install_dependencies"
      
      - name: Build and Publish Windows(Unsigned)
        uses: "./.github/workflows/steps/build_windows"
        with:
          package-id: "WindowsUnsigned"
          project-to-build: "MyExtensionsApp.Windows/MyExtensionsApp.Windows.csproj"  
          project-folder: "MyExtensionsApp.Windows"            

  build_linux:
    name: Build Linux
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0 
      - name: Install Dependencies
        uses: "./.github/workflows/steps/install_dependencies"
      
      - name: Build Linux
        uses: "./.github/workflows/steps/build_desktop"
        with:
          package-id: "Linux"
          project-to-build: "MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.csproj"  

  build_wpf:
    name: Build WPF
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0 
      - name: Install Dependencies
        uses: "./.github/workflows/steps/install_dependencies"
      
      - name: Build WPF
        uses: "./.github/workflows/steps/build_desktop"
        with:
          package-id: "WPF"
          project-to-build: "MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.csproj"  

  build_gtk:
    name: Build Gtk
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0 
      - name: Install Dependencies
        uses: "./.github/workflows/steps/install_dependencies"
        with:
          install-gtk: 'true'
              
      - name: Build GTK
        uses: "./.github/workflows/steps/build_desktop"
        with:
          package-id: "GTK"
          project-to-build: "MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.csproj"

    ###################################################
    #                 IMPORTANT                       #
    # Store base64 certificates in your repo secrets  #
    # then just replace the commented base64 variables#
    # down below by your new secret variables         #
    ###################################################

  # build_android_signed:
  #   name: Build and Sign Android
  #   runs-on: windows-latest
  #   timeout-minutes: 60
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0 
  #     - name: Install Dependencies
  #       uses: "./.github/workflows/steps/install_dependencies"
      
  #     - name: Build and Sign Mobile (Android)
  #       uses: "./.github/workflows/steps/build_android"
  #       with:
  #         sign-package: 'true'
  #         package-id: "signed_android"
  #         certificate:  "${{ secrets.ANDROID_BASE64_JKS_CERTIFICATE }}"
  #         certificate-password:  "${{ secrets.ANDROID_JKS_CERTIFICATE_PASSWORD }}"
  #         certificate-alias:  "${{ secrets.ANDROID_JKS_CERTIFICATE_ALIAS }}"
  #         project-to-build: "MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.csproj" 

  # build_windows_signed:
  #   name: Build and Sign Windows
  #   runs-on: windows-latest
  #   timeout-minutes: 60
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0 
  #     - name: Install Dependencies
  #       uses: "./.github/workflows/steps/install_dependencies"
            
  #     - name: Build and Publish Windows(Signed)
  #       uses: "./.github/workflows/steps/build_windows"
  #       with:
  #         package-id: "signed_windows"
  #         certificate: "${{ secrets.WINDOWS_BASE64_PFX_CERTIFICATE }}"
  #         project-to-build: "MyExtensionsApp.Windows/MyExtensionsApp.Windows.csproj"  
  #         project-folder: "MyExtensionsApp.Windows"

  # build_ios_signed:
  #   name: Build and Sign iOS
  #   runs-on: macos-latest
  #   timeout-minutes: 60
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0 
  #     - name: Install Dependencies
  #       uses: "./.github/workflows/steps/install_dependencies"     
  #       with:
  #         install-windowsSDK: 'false'
      
  #     - name: Build Mobile (iOS)
  #       uses: "./.github/workflows/steps/build_ios"
  #       with:
  #         package-id: "signed_ios"
  #         certificate: "${{ secrets.BASE64_P12_CERTIFICATE }}"
  #         certificate-password: "${{ secrets.BASE64_P12_PASSWORD }}"
  #         provisioning-profile: "${{ secrets.BASE64_PROV_PROFILE }}"
  #         project-folder: 'MyExtensionsApp.Mobile'
  #         project-to-build: "MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.csproj" 
